export const Types = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCES: "LOGIN_SUCCES",
    LOGIN_ERROR: "LOGIN_ERROR",
    LOGIN_SIGN_IN: "LOGIN_SIGN_IN",
    LOGIN_SIGN_IN_SUCCES: "LOGIN_SIGN_IN_SUCCES",
    LOGIN_SIGN_IN_ERROR: "LOGIN_SIGN_IN_ERROR",
    LOGOUT: "LOGOUT"
} 